name: Rally Point Wines
favicon: null
layout_spectrum: 0.50097
typography_spectrum: 0.6673
title: Rally Point Wines - Wine on a Mission
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-39098989-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78574e'
    - '#ffffff'
    - '#000000'
    - '#aaaaaa'
    - '#ff0000'
  brandStrength: 0.875
  lightness: 0.8639339546207339
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
